name: Deploy
on:
  push:
    branches:
      - master
      - dev
jobs:
  Deploy:
    if: github.repository == 'hasadna/anyway'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.0.1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: anywayteam/anyway
        tag_with_ref: false
        tag_with_sha: true
